import CharacterCard from '@/components/cards/character/CharacterCard';
import { mockCharacterCardProps } from '@/components/cards/character/CharacterCard.mocks';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">The Rick and Morty API</a>
        </h1>

        <div>
          <CharacterCard {...mockCharacterCardProps.base} />
          <CharacterCard {...mockCharacterCardProps.base} />
          <CharacterCard {...mockCharacterCardProps.base} />
          <CharacterCard {...mockCharacterCardProps.base} />
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
