/* eslint-disable @next/next/no-page-custom-font */
import Home from "@/components/home/Home";
import { ThemeProvider } from "@emotion/react";
import { createTheme } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});

const App: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <ThemeProvider theme={darkTheme}>
        <main>
          <Home />
        </main>
      </ThemeProvider>
    </div>
  );
};

export default App;
